# NumPy
Ref:
Official NumPy website: https://numpy.org/doc/stable/user/absolute_beginners.html

"NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems."

## Installations 

conda install numpy

or

pip install numpy 

## importing numpy

In [1]:
import numpy as np

## numpy array
NumPy arrays are faster and more compact than Python lists. Unlike python lists, All of the elements in a NumPy array should be homogeneous.

In [5]:
# Creating numpy array from a list 
lst = [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [4]:
np.array(lst)

array([1, 2, 3, 4, 5])

In [2]:
### from a  nested list (matrix)
my_list = [[1,2,3],[4,5,6],[100,200,300]]
my_list

[[1, 2, 3], [4, 5, 6], [100, 200, 300]]

In [10]:
myarr = np.array(my_list)
myarr

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300]])

In [16]:
#accessing the array using index position
myarr[0]

array([1, 2, 3])

In [18]:
myarr[0][2]

3

In [19]:
myarr[0][-1]

3

## Creating array from built-in methods 
* np.array()
* np.arange()
* np.linspace()
* np.zeros()
* np.ones()
* np.empty()
* np.eye()

### np.arange()
Return evenly spaced values within a given interval.

arange([start,] stop[, step,], dtype=None)

In [28]:
np.arange(3) #not including 3

array([0, 1, 2])

In [23]:
np.arange(1,3) #starting from 1 to 2 

array([1, 2])

In [24]:
np.arange(1,5,2) #step size is 2

array([1, 3])

In [30]:
np.arange(1,7,dtype=float) # dtype is float

array([1., 2., 3., 4., 5., 6.])

### np.linspace()

Return evenly spaced numbers over a specified interval.

In [36]:
np.linspace(1,4) #default num = 50 

array([1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
       1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
       1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
       1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
       2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
       2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
       2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
       3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
       3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
       3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ])

In [39]:
np.linspace(1,4,4) #want to generate 4 numbers

array([1., 2., 3., 4.])

### np.zeros() and np.ones and np.empty()

In [40]:
#Return a new array of given shape and type, filled with zeros.
np.zeros(5) #1-d zero array

array([0., 0., 0., 0., 0.])

In [44]:
np.zeros((2,2)) #2x2 zero matrix 

array([[0., 0.],
       [0., 0.]])

In [45]:
#Return a new array of given shape and type, filled with ones.
np.ones(4)

array([1., 1., 1., 1.])

In [46]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.empty(4) #an empty array of given size

array([1., 1., 1., 1.])

In [69]:
myarr = np.empty((2,3))
myarr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [68]:
myarr[0]

array([1., 2., 3.])

### np.eye()

Return a 2-D array with ones on the diagonal and zeros elsewhere.


In [70]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Creating array from random numbers

#### np.random.rand()
Create an array of the given shape and populate it with random samples from a **uniform** distribution over [0, 1).

In [75]:
np.random.rand(2) #2 elements 

array([0.67914005, 0.47293362])

In [77]:
np.random.rand(2,3) #2x3 matrix

array([[0.62133747, 0.92934127, 0.19286938],
       [0.81070331, 0.23462592, 0.88375429]])

### np.random.randn()
Return a sample (or samples) from the "standard normal" distribution.

In [78]:
np.random.randn()

0.3650056915243174

In [79]:
np.random.randn(2)

array([-1.26237741, -2.0805253 ])

In [80]:
np.random.randn(2,3)

array([[-0.30314163, -0.01718924,  0.22655572],
       [-0.59250614,  1.07654106, -2.33665157]])

### np.random.randint()
Return random integers from `low` (inclusive) to `high` (exclusive).

In [83]:
np.random.randint(4)

3

In [84]:
np.random.randint(1,4)

2

In [85]:
np.random.randint(1,4,size=4)

array([1, 1, 1, 3])

In [86]:
np.random.randint(1,4,size=(3,4))

array([[2, 1, 2, 2],
       [1, 3, 3, 3],
       [1, 1, 3, 2]])

### np.random.random()
Return random floats in the half-open interval [0.0, 1.0).

In [95]:
np.random.random()

0.06463052467898733

In [96]:
np.random.random((2,3))

array([[0.63745535, 0.94671936, 0.69375625],
       [0.58239012, 0.40164006, 0.60632313]])

## Array attributes and methods 

In [98]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [99]:
#to see the shape of the array 
arr.shape

(25,)

#### arr.reshape()
Returns an array containing the same data with a new shape.

In [101]:
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [103]:
ranarr = np.random.randint(0,50,50) #an random arry of 50 elements
ranarr

array([38, 47, 41,  5, 13,  4, 11,  9, 21,  5, 43, 19, 30, 43,  0,  6,  9,
       19,  0, 47,  7, 12, 29, 38, 15, 45, 12,  8,  0, 17,  8, 37, 13, 33,
       40, 43,  5,  2, 21, 26, 43,  9, 30, 23, 45, 41, 42, 24, 37, 11])

In [104]:
ranarr.shape

(50,)

In [113]:
randarr = ranarr.reshape(5,10)
randarr

array([[38, 47, 41,  5, 13,  4, 11,  9, 21,  5],
       [43, 19, 30, 43,  0,  6,  9, 19,  0, 47],
       [ 7, 12, 29, 38, 15, 45, 12,  8,  0, 17],
       [ 8, 37, 13, 33, 40, 43,  5,  2, 21, 26],
       [43,  9, 30, 23, 45, 41, 42, 24, 37, 11]])

In [129]:
randarr.shape #new shape

(5, 10)

In [131]:
randarr.reshape(25,2)

array([[38, 47],
       [41,  5],
       [13,  4],
       [11,  9],
       [21,  5],
       [43, 19],
       [30, 43],
       [ 0,  6],
       [ 9, 19],
       [ 0, 47],
       [ 7, 12],
       [29, 38],
       [15, 45],
       [12,  8],
       [ 0, 17],
       [ 8, 37],
       [13, 33],
       [40, 43],
       [ 5,  2],
       [21, 26],
       [43,  9],
       [30, 23],
       [45, 41],
       [42, 24],
       [37, 11]])

### ndim
dimensions of the array

In [115]:
#dimensions of the array
randarr.ndim

2

### size
total number of elements in the array

In [118]:
randarr.size

50

### min,max,argmin,argmx
for finding min, max values or finding their respective locations

In [121]:
#min. value
randarr.min()

0

In [123]:
#max value 
randarr.max()

47

In [125]:
## Return indices of the minimum value
randarr.argmin()

14

In [126]:
#Return indices of the maximum values along the given axis.
randarr.argmax()

1

### dtype
return data type of the object

In [128]:
randarr.dtype

dtype('int64')

In [2]:
import numpy as np

In [3]:
np.random.random()

0.38490054137376073

In [4]:
np.random.random_sample()

0.6519388965822374