# Array indexing and slicing 

Ref link: https://numpy.org/doc/stable/user/absolute_beginners.html#indexing-and-slicing

Indexing and slicing work similary like python's list  

## Indexing

In [2]:
import numpy as np

In [3]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#grabbing first item
arr[0]

1

In [5]:
#grabbing Last item
arr[-1]

9

## Slicing

In [6]:
#slicing array
arr[0:5]

array([1, 2, 3, 4, 5])

In [7]:
#slicing with step size
arr[0:5:2]

array([1, 3, 5])

In [8]:
#slicing using negative indexing
arr[-3:]

array([7, 8, 9])

### slicing based on certain condition

In [9]:
#find booleans 
arr<5

array([ True,  True,  True,  True, False, False, False, False, False])

In [10]:
#apply booleans to find the numbers 
#<5
arr[arr<5]

array([1, 2, 3, 4])

In [11]:
# >6
arr[arr>6]

array([7, 8, 9])

In [12]:
#find even numbers
arr[arr%2==0]

array([2, 4, 6, 8])

In [13]:
#find number in between 
arr[(arr>2) & (arr<6)]

array([3, 4, 5])

## Broadcasting 
Sometimes you might want to perform a same operation to all numbers or a set a sumbers

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#broadcasting to all
arr*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
#broadcasting to some numbers
arr[0:3] = 99
arr

array([99, 99, 99,  4,  5,  6,  7,  8,  9])

### Broadcasting to a slice of arry

In [17]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr_slice = arr[0:5]
arr_slice

array([0, 1, 2, 3, 4])

In [19]:
arr_slice[:] = 99

In [20]:
arr_slice

array([99, 99, 99, 99, 99])

In [21]:
#Slicing changes also affects the original array 
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

### copying an array

In [22]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr_copy = arr.copy()
arr_copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr_copy[0:5] = 99
arr_copy

array([99, 99, 99, 99, 99,  6,  7,  8,  9])

In [25]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

See, arr_copy does not impact on arr array  

## 2D array indexing 
arr[row][col] or arr[row,col]

In [26]:
arr = np.array([
    [1,2,3],
    [10,20,30],
    [11,21,31]
])
arr

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 21, 31]])

In [27]:
#grabbing first row
arr[0]

array([1, 2, 3])

In [28]:
#grabbing last  row
arr[-1]

array([11, 21, 31])

In [29]:
#grabbing a single item 
arr[0][1]

2

In [30]:
#this also works 
arr[0,1]

2

#### slicing 2d array

In [31]:
arr

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 21, 31]])

In [32]:
#grabbing top left square
arr[:2,:2]

array([[ 1,  2],
       [10, 20]])

In [33]:
#grabbing top right square
arr[0:2,1:]

array([[ 2,  3],
       [20, 30]])

In [34]:
#grabbing bottom left square
arr[1:,:2]

array([[10, 20],
       [11, 21]])

In [35]:
#grabbing bottom right 
arr[1:,1:]

array([[20, 30],
       [21, 31]])

## Fancy indexing 
we can see the matrix in different row order 

In [36]:
#Create an arry
my_arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
my_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
#row order 2 and 0
my_arr[[2,0]]

array([[7, 8, 9],
       [1, 2, 3]])

In [38]:
# row order reverse 
my_arr[[2,1,0]]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

## Creating array from existing array(s)

In [54]:
#lets create an array
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
#getting a new array
arr1 = arr[5:9]
arr1

array([6, 7, 8, 9])

In [56]:
#getting anorther array based on a condition
arr2 = arr[arr<5]
arr2

array([1, 2, 3, 4])

### array concatanation 

In [57]:
#Join a sequence of arrays along an existing axis.
np.concatenate((arr1,arr2))

array([6, 7, 8, 9, 1, 2, 3, 4])

### array stack: horizontally and vertically 

In [43]:
arr1 

array([6, 7, 8, 9])

In [44]:
arr2

array([1, 2, 3, 4])

In [45]:
np.vstack((arr1,arr2))

array([[6, 7, 8, 9],
       [1, 2, 3, 4]])

In [46]:
np.hstack((arr1,arr2))

array([6, 7, 8, 9, 1, 2, 3, 4])

### 2d array stacking example 

In [47]:
arr1 = np.array([
    [1,1],
    [2,2]
])
arr1

array([[1, 1],
       [2, 2]])

In [48]:
arr2 = np.array([
    [3,3],
    [4,4]
])
arr2

array([[3, 3],
       [4, 4]])

In [49]:
np.vstack((arr1,arr2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [50]:
np.hstack((arr1,arr2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [51]:
## concatanation with axis=1 give the same result (horizontal stacking)
np.concatenate((arr1,arr2),axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [52]:
np.concatenate((arr1,arr2)) #default axis =0 (same as vertical stack) 

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])