Ref link: https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations

In [1]:
#lets create an array 
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr_one = np.ones(10)
arr_one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
arr_one = arr_one*5

In [4]:
arr_one

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## Arithmetic operations (+,-,*,/)

In [5]:
arr + arr_one

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [6]:
arr - arr_one

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [7]:
arr*arr_one

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [8]:
arr/arr_one

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

## numpy universal functions 
Ref: https://numpy.org/doc/stable/reference/ufuncs.html

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#element-wise sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
#element-wise square 
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
#exponential of all elements 
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [13]:
#performing log10 element-wise 
np.log10(arr)

<ipython-input-13-57b4272742da>:2: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [14]:
#performing log2 element-wise 
np.log2(arr)

<ipython-input-14-9cc30c147f84>:2: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [15]:
#finding max
np.max(arr)

9

In [16]:
#same as this 
arr.max()

9

In [17]:
#finding min value 
np.min(arr)

0

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#doing power element-wise 
np.power(arr,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## find greater items from arr one comapre to arr_one

In [20]:
boolean =  np.greater(arr,arr_one)
boolean

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [21]:
arr[boolean]

array([6, 7, 8, 9])

In [22]:
#same as 
arr[arr>arr_one]

array([6, 7, 8, 9])

### finding unique number 

In [23]:
arr = np.array([1,2,3,3,4,5,6,1])
arr

array([1, 2, 3, 3, 4, 5, 6, 1])

In [24]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

### sorting 

In [25]:
np.sort(arr)

array([1, 1, 2, 3, 3, 4, 5, 6])

### dimensions, size and shape 

In [26]:
#number of dimension
arr.ndim

1

In [27]:
#Number of array elements 
arr.size

8

In [28]:
#The shape of an array is the number of elements in each dimension.
arr.shape

(8,)

The arr has one dimension with 8 elements 

### sum of elements

In [29]:
arr

array([1, 2, 3, 3, 4, 5, 6, 1])

In [30]:
np.sum(arr)

25

In [31]:
arr2d = np.array([
    [1,1],
    [2,2]
])
arr2d

array([[1, 1],
       [2, 2]])

In [32]:
np.sum(arr2d) #sum for all element 

6

In [33]:
np.sum(arr2d,axis=0) #column-wise sum 

array([3, 3])

In [34]:
np.sum(arr2d,axis=1) #row-wise sum

array([2, 4])

### reversing an array

In [35]:
arr

array([1, 2, 3, 3, 4, 5, 6, 1])

In [36]:
arr

array([1, 2, 3, 3, 4, 5, 6, 1])

In [37]:
np.flip(arr)

array([1, 6, 5, 4, 3, 3, 2, 1])

### reshapping an 1-D array 

In [38]:
arr.shape

(8,)

In [39]:
arr = arr.reshape(1,8)
arr

array([[1, 2, 3, 3, 4, 5, 6, 1]])

In [40]:
arr.shape

(1, 8)

### tranposing a 2D array 

Returns a view of the array with axes transposed.

In [4]:
arr2d = np.array([
    [1,2,3],
    [4,5,6]
  
])
arr2d.shape

(2, 3)

In [7]:
arr2d_trans = arr2d.transpose() 
arr2d_trans

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
arr2d_trans.shape

(3, 2)

arr2d_transpose has 2 dimensions, first dimension has 3 elements and second dimenstion has 2 elements

**Good Job**